### ISSUE TITLE
throughtput not as expected

### ISSUE THREAD

**Issue by wlwl1011** [SoonyangZhang/quic-on-ns3#11]
Hello !
I want to ask you about throughtput, when using dumpbell mode (--topo = dumpbell)
I'm sorry to bother you again today.
Thank you so much for letting me know every time I'm lacking.
So let me tell you what I'm curious about.

Looking at the code below, I thought it was a code that sets the link to be delayed! The experiment I wanted didn't need a link delay, so I gave 0 to the link delay.
![Untitled](https://github.com/SoonyangZhang/quic-on-ns3/assets/62577565/42e2de7f-f41e-46a1-9793-28449883215a)

However, after removing the link delay, the throughput is measured strangely.
Approximately 1500 kbps is measured.
Originally, 5000 kbps was measured when there was as much link delay as od. 
Why is this error happening?

I looked up related documents about this for two days, and I opened all the quic models written by Soonyanhzzang, but I couldn't solve them...
If you know, please reply.

**Comment by SoonyangZhang** [comment]
Google what is the difference between queue and queue discipline in ns3？ the low throughput is caused by shallow buffer in netdev.



---Original---
From: ***@***.***&gt;
Date: Wed, Aug 2, 2023 22:53 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [SoonyangZhang/quic-on-ns3] throughtput not as expected (Issue #11)




 
Hello !
 I want to ask you about throughtput, when using dumpbell mode (--topo = dumpbell)
 I'm sorry to bother you again today.
 Thank you so much for letting me know every time I'm lacking.
 So let me tell you what I'm curious about.
 
Looking at the code below, I thought it was a code that sets the link to be delayed! The experiment I wanted didn't need a link delay, so I gave 0 to the link delay.
 
 
However, after removing the link delay, the throughput is measured strangely.
 Approximately 1500 kbps is measured.
 Originally, 5000 kbps was measured when there was as much link delay as od.
 Why is this error happening?
 
I looked up related documents about this for two days, and I opened all the quic models written by Soonyanhzzang, but I couldn't solve them...
 If you know, please reply.

**Comment by wlwl1011** [comment]
Oh, I got it !
First of all, I am very sorry to bother you every time with my shallow knowledge of NS3. I read what the original author said and studied the content. 😀
 the low throughput issue observed when setting the link delay to 0 might be caused by the shallow buffer in the network device (netdev), right?
 According to the research based on the original author's words, there seems to be the following reasons for this situation, so please check if it fits the intention you mentioned! 🥹🥹🥹

The netdev (network device) in NS3 typically has a buffer that temporarily stores packets before they are transmitted over the link. If the buffer size is too small (shallow buffer), it can lead to packet drops and reduced throughput, especially in scenarios with high network congestion or when the sending rate exceeds the capacity of the buffer.

When you set the link delay to 0, the packets might be transmitted very quickly between nodes, leading to higher congestion in the shallow buffer of the netdev, resulting in packet drops and lower throughput!
